# Generated by Django 4.2.1 on 2023-08-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_social_item_image_social_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_item',
            name='title',
        ),
    ]
