# Generated by Django 4.2.1 on 2023-08-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_social_item_type_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
                ('bg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bg', to='frontend.image')),
                ('main_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainSlider', to='frontend.image')),
            ],
        ),
    ]
