# Generated by Django 4.2.1 on 2023-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_main_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
