# Generated by Django 4.2.1 on 2023-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_main_slider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_slider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
