# Generated by Django 4.2.1 on 2023-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_main_slider_body_alter_main_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('خبر', 'خبر'), ('منتج', 'منتج')], max_length=20, null=True)),
            ],
        ),
    ]
