# Generated by Django 4.2.1 on 2023-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(blank=True, choices=[('news', 'خبر'), ('product', 'منتج')], max_length=20, null=True),
        ),
    ]
