# Generated by Django 4.2.1 on 2023-09-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_page_is_active_page_is_visible_alter_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=10000)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('main_img', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='frontend.image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='frontend.page')),
            ],
        ),
    ]
