# Generated by Django 4.2.1 on 2023-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_nav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='main_slider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
