# Generated by Django 4.2.1 on 2023-09-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_post_more_info_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(blank=True, choices=[('news', 'خبر'), ('product', 'منتج'), ('announcement', 'إعلان')], max_length=20, null=True),
        ),
    ]
