# Generated by Django 4.2.1 on 2023-09-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_alter_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(blank=True, choices=[('news', 'خبر'), ('product', 'منتج'), ('announcement', 'إعلان'), ('post', 'منشور')], max_length=20, null=True),
        ),
    ]
