# Generated by Django 4.2.1 on 2023-09-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_subpage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
