# Generated by Django 4.2.1 on 2023-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_item',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='social_item',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
